### ISSUE TITLE
Início da gramática

### ISSUE THREAD

**Issue by joaobarbirato** [joaobarbirato/compilador-wallpaper#1]
A gramática deve permitir:
- Declaração de imagens
- Declaração de cores
- Desenhar

**Comment by cassianomaia** [comment]
- Declaração de imagens pode conter:
   - Nome da imagem (para salvar no final, e atribuir coisas)
   - Tamanho total da imagem (Para futuramente analisar semanticamente se o tamanho está ok)
   - Cor de fundo
   - Nro max de elementos que podemos adcionar (?)
